[phases.setup]
nixPkgs = ["nodejs_20", "postgresql_15"]

[phases.install]
cmds = ["npm install --legacy-peer-deps --no-optional"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[env]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1" 