[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300

[env]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_20", "postgresql_15"]

[phases.install]
cmds = ["npm install --legacy-peer-deps --no-optional"]

[phases.build]
cmds = ["chmod +x build.sh", "./build.sh"] 